/// @notice Withdraw `amount` of underlying tokens from the strategy back to the vault.
/// @param amount The amount of underlying tokens to withdraw.
function withdraw(uint256 amount) external;

/// @notice Withdraw all funds from the strategy back to the vault.
function withdrawAll() external;

/// @notice Harvest any rewards / yields generated by the strategy and convert them to underlying.
/// @dev Implementations should transfer realized underlying back to the vault contract.
function harvest() external;

/// @notice Get total underlying amount currently managed by the strategy.
/// @return totalUnderlying The amount of underlying tokens the strategy currently manages.
function balanceOf() external view returns (uint256 totalUnderlying);
